#ifndef RETRO_NGA_C_LAYOUT_H
#define RETRO_NGA_C_LAYOUT_H

/* Generated by tools/generate-layout. */

#define RETRO_IMAGE_DICTIONARY         2
#define RETRO_IMAGE_HEAP               3
#define RETRO_IMAGE_VERSION            4
#define RETRO_IMAGE_INTERPRET          5
#define RETRO_IMAGE_NOTFOUND           6
#define RETRO_IMAGE_TIB                7
#define RETRO_IMAGE_TIB_END            8
#define RETRO_IMAGE_DICTHASH           9
#define RETRO_IMAGE_DICTREHASH         10

#define RETRO_DICT_OFFSET_LINK         0
#define RETRO_DICT_OFFSET_XT           1
#define RETRO_DICT_OFFSET_CLASS        2
#define RETRO_DICT_OFFSET_SOURCE       3
#define RETRO_DICT_OFFSET_HASH         4
#define RETRO_DICT_OFFSET_STACK        5
#define RETRO_DICT_OFFSET_ASTACK       6
#define RETRO_DICT_OFFSET_FSTACK       7
#define RETRO_DICT_OFFSET_DESCR        8
#define RETRO_DICT_OFFSET_NAME         9

#endif
