/**************************************************************
                _              __            _   _
       _ __ ___| |_ _ __ ___  / _| ___  _ __| |_| |__
      | '__/ _ \ __| '__/ _ \| |_ / _ \| '__| __| '_ \
      | | |  __/ |_| | | (_) |  _| (_) | |  | |_| | | |
      |_|  \___|\__|_|  \___/|_|  \___/|_|   \__|_| |_|
                                                for nga

      (c) Charles Childers, Luke Parrish, Marc Simpsonn,
          Jay Skeer, Kenneth Keating

**************************************************************/

#ifndef RETRO_NGA_CORE_H
#error "retro_modules.c must be included after nga_core.h"
#endif

/* Include Module Order -----------------------------------------------
  image.c is generated by the build and must be included before this
  file, as it provides the embedded image data consumed by nga_core.c.
  nga_core.c provides stack, image, execution, and opcode primitives.
  string_handling.c provides UTF/string helpers used by host I/O,
  devices, and scripting.
  scripting.c depends on both the VM core and string helpers.
  --------------------------------------------------------------------*/

#include "nga_core.c"

#include "string_handling.c"

#ifdef ENABLE_IOCTL
#include "dev-ioctl.c"
#endif

#ifdef ENABLE_MALLOC
#ifdef BIT64
#include "dev-malloc.c"
#endif
#endif

#ifdef ENABLE_ERROR
#include "dev-error.c"
#endif

#ifdef ENABLE_BLOCKS
#include "dev-blocks.c"
#endif

#ifdef ENABLE_FILES
#include "dev-files.c"
#endif

#ifdef ENABLE_MULTICORE
#include "dev-multicore.c"
#endif

#ifdef ENABLE_FFI
#include "dev-ffi.c"
#endif

#ifdef ENABLE_FLOATS
#include "dev-float.c"
#endif

#ifdef ENABLE_CLOCK
#include "dev-clock.c"
#endif

#ifdef ENABLE_RNG
#include "dev-rng.c"
#endif

#ifdef ENABLE_SOCKETS
#include "dev-sockets.c"
#endif

#ifdef ENABLE_UNIX
#include "dev-unix.c"
#endif

#include "scripting.c"
