/**************************************************************
                _              __            _   _
       _ __ ___| |_ _ __ ___  / _| ___  _ __| |_| |__
      | '__/ _ \ __| '__/ _ \| |_ / _ \| '__| __| '_ \
      | | |  __/ |_| | | (_) |  _| (_) | |  | |_| | | |
      |_|  \___|\__|_|  \___/|_|  \___/|_|   \__|_| |_|
                                                for nga

      (c) Charles Childers, Luke Parrish, Marc Simpsonn,
          Jay Skeer, Kenneth Keating

**************************************************************/

#ifndef RETRO_NGA_CORE_H
#error "retro_modules.c must be included after nga_core.h"
#endif

/* Include Module Order -----------------------------------------------
  image.c is generated by the build and must be included before this
  file, as it provides the embedded image data consumed by nga_core.c.
  nga_core.c provides stack, image, execution, and opcode primitives.
  string_handling.c provides UTF/string helpers used by host I/O,
  devices, and scripting.
  scripting.c depends on both the VM core and string helpers.
  --------------------------------------------------------------------*/

#include "nga_core.c"

#include "string_handling.c"

#define DEVICE_IMPLEMENTATIONS
#define DEVICE(name)
#define DEVICE_WITH_INIT(name, init)
#include "devices.def"
#undef DEVICE_WITH_INIT
#undef DEVICE
#undef DEVICE_IMPLEMENTATIONS
