.Dd May 2019
.Dt RETRO-DESCRIBE 1
.Os
.Sh RETRO-DESCRIBE
.Nm retro-describe
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
wordname
.Op additional wordnames
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is a tool for looking up the description and stack comments for
words in the core language and extensions.  It will write output
to stdout.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
