.Dd August 2019
.Dt RETRO-TAGS 1
.Os
.Sh RETRO-TAGS
.Nm retro-tags
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is a tool for extracting code from fenced blocks in literate
sources and generating a tags file compatible with ctags.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
