.Dd May 2019
.Dt RETRO-DOCUMENT 1
.Os
.Sh RETRO-DOCUMENT
.Nm retro-document
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
filename
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is a tool for generating a listing of the descriptions and stack
comments for all standard word used in a source file. It will
write output to stdout.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
