.Dd January 2019
.Dt RETRO-RI 1
.Os
.Sh RETRO-RI
.Nm retro-ri
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
Retro is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is an interactive, curses based interface for Retro.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
