.Dd January 2019
.Dt RETRO 1
.Os
.Sh RETRO
.Nm retro
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
[options]
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is the main interface for interacting with
Retro. It provides both an interactive and a 
scripting model.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
