.Dd November 2023
.Dt RETRO-COMPILER 1
.Os
.Sh RETRO-COMPILER
.Nm retro-compiler
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
filename
entry
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
takes a source file you provide and compiles it into a new
image. The new image is then bundled with a RetroForth runtime
and saved as a new executable named `a.out`.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
