.Dd February 2019
.Dt RETRO-MURI 1
.Os
.Sh RETRO-MURI
.Nm retro-muri
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
filename
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is an assembler for Nga, the virtual machine at the heart of
Retro. It is used to build the image file containing the actual
Retro language.

This will extract the code blocks in the specified file and
generate an image file named `ngaImage`.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
