.Dd February 2019
.Dt RETRO-EXTEND 1
.Os
.Sh RETRO-EXTEND
.Nm retro-extend
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
image filename
.Op filenames
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is a tool to load additional code into an image file. It takes
the name of an image file and one or more source files to load
into the image. After completion the image file will be updated
with the changes.

.Sh CAVETS
.Nm
only emulates the minimal console output device. If the source
files require additional I/O to be present, the extend process
will likely fail to work correctly.

.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
