.Dd June 2020
.Dt RETRO-UNU 1
.Os
.Sh RETRO-UNU
.Nm retro-unu
.Nd "literate programming tool for use with retro"
.Sh SYNOPSIS
.Nm
.Op Fl t
filename
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is a tool for extracting code from literate sources. It will
write output to stdout.

A code block starts with ~~~ on a line by itself and ends with
a second ~~~. Test blocks start and end with ```.

.Nm
does not support "out of order" structuring of the code,
commentary, and test blocks.

.Sh OPTIONS
.Bl -tag -width -indent
.It Fl t
Include any test blocks in the file.
.It filename
Extract code blocks from the specified file.
.El
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com

