.Dd January 2019
.Dt RETRO-MURI 1
.Os
.Sh RETRO-MURI
.Nm retro-muri
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
[options]
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is an assembler for Nga, the virtual machine at the heart of
Retro. It is used to build the image file containing the actual
Retro language.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
