.Dd January 2019
.Dt RETRO-UNU 1
.Os
.Sh RETRO-UNU
.Nm retro-unu
.Nd "a modern, pragmatic forth development system"
.Sh SYNOPSIS
.Nm
filename
.Sh DESCRIPTION
RETRO is a modern, pragmatic Forth drawing influences from many
sources. It's clean, elegant, tiny, and easy to grasp and adapt
to various uses.

.Nm
is a tool for extracting code from fenced blocks in literate
sources. It will write output to stdout.
.Sh AUTHORS
.An Charles Childers Aq Mt crc@forthworks.com
