// Generated by tools/generate-layout.

pub const IMAGE_DICTIONARY: usize = 2;
pub const IMAGE_HEAP: usize = 3;
pub const IMAGE_VERSION: usize = 4;
pub const IMAGE_INTERPRET: usize = 5;
pub const IMAGE_NOTFOUND: usize = 6;
pub const IMAGE_TIB: usize = 7;
pub const IMAGE_TIB_END: usize = 8;
pub const IMAGE_DICTHASH: usize = 9;
pub const IMAGE_DICTREHASH: usize = 10;

pub const DICT_OFFSET_LINK: usize = 0;
pub const DICT_OFFSET_XT: usize = 1;
pub const DICT_OFFSET_CLASS: usize = 2;
pub const DICT_OFFSET_SOURCE: usize = 3;
pub const DICT_OFFSET_HASH: usize = 4;
pub const DICT_OFFSET_STACK: usize = 5;
pub const DICT_OFFSET_ASTACK: usize = 6;
pub const DICT_OFFSET_FSTACK: usize = 7;
pub const DICT_OFFSET_DESCR: usize = 8;
pub const DICT_OFFSET_NAME: usize = 9;
