PYTHON ?= python3

default:
	cp ngaImage pythonImage
	$(PYTHON) tools/retro-extend.py pythonImage interface/clock.retro interface/filesystem.retro interface/floatingpoint.retro interface/rng.retro	
	$(PYTHON) tools/retro-embedimage.py pythonImage >vm/nga-python/InitialImage.py
	rm -f pythonImage
