#!/bin/sh

echo "no"; retro-muri no.muri ; retro -r ngaImage; rm -f ngaImage
#echo "li"; retro-muri li.muri ; retro -r ngaImage; rm -f ngaImage
echo "du"; retro-muri du.muri ; retro -r ngaImage; rm -f ngaImage
echo "dr"; retro-muri dr.muri ; retro -r ngaImage; rm -f ngaImage
echo "sw"; retro-muri sw.muri ; retro -r ngaImage; rm -f ngaImage
echo "pu"; retro-muri pu.muri ; retro -r ngaImage; rm -f ngaImage
echo "po"; retro-muri po.muri ; retro -r ngaImage; rm -f ngaImage
echo "ju"; retro-muri ju.muri ; retro -r ngaImage; rm -f ngaImage
echo "ca"; retro-muri ca.muri ; retro -r ngaImage; rm -f ngaImage
echo "cc"; retro-muri cc.muri ; retro -r ngaImage; rm -f ngaImage
echo "re"; retro-muri re.muri ; retro -r ngaImage; rm -f ngaImage
echo "eq"; retro-muri eq.muri ; retro -r ngaImage; rm -f ngaImage
echo "ne"; retro-muri ne.muri ; retro -r ngaImage; rm -f ngaImage
echo "lt"; retro-muri lt.muri ; retro -r ngaImage; rm -f ngaImage
echo "gt"; retro-muri gt.muri ; retro -r ngaImage; rm -f ngaImage
echo "fe"; retro-muri fe.muri ; retro -r ngaImage; rm -f ngaImage
echo "st"; retro-muri st.muri ; retro -r ngaImage; rm -f ngaImage
echo "ad"; retro-muri ad.muri ; retro -r ngaImage; rm -f ngaImage
echo "su"; retro-muri su.muri ; retro -r ngaImage; rm -f ngaImage
echo "mu"; retro-muri mu.muri ; retro -r ngaImage; rm -f ngaImage
echo "di"; retro-muri di.muri ; retro -r ngaImage; rm -f ngaImage
#echo "an"; retro-muri an.muri ; retro -r ngaImage; rm -f ngaImage
#echo "or"; retro-muri or.muri ; retro -r ngaImage; rm -f ngaImage
#echo "xo"; retro-muri xo.muri ; retro -r ngaImage; rm -f ngaImage
echo "sh"; retro-muri sh.muri ; retro -r ngaImage; rm -f ngaImage
echo "zr"; retro-muri zr.muri ; retro -r ngaImage; rm -f ngaImage
echo "ha"; retro-muri ha.muri ; retro -r ngaImage; rm -f ngaImage
