# Generated by tools/generate-layout.

IMAGE = {
    "Dictionary": 2,
    "Heap": 3,
    "Version": 4,
    "interpret": 5,
    "NotFound": 6,
    "TIB": 7,
    "TIB_END": 8,
    "DictHash": 9,
    "DictRehash": 10,
}

DICTIONARY = {
    "link": 0,
    "xt": 1,
    "class": 2,
    "source": 3,
    "hash": 4,
    "stack": 5,
    "astack": 6,
    "fstack": 7,
    "descr": 8,
    "name": 9,
}
