#!/usr/bin/env python3

"""Generate RETRO layout constants from tools/layout/*.tsv."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
LAYOUT = ROOT / "tools" / "layout"


def read_layout(path):
    entries = []
    for raw_line in path.read_text(encoding="ascii").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line or line.startswith("#"):
            continue
        name, value = line.split(None, 1)
        entries.append((name, int(value)))
    return entries


def const_name(prefix, name):
    chars = []
    for char in name:
        if char.isalnum():
            chars.append(char.upper())
        else:
            chars.append("_")
    return prefix + "".join(chars)


def write_c_header(path, guard, image, dictionary):
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* Generated by tools/generate-layout. */",
        "",
    ]
    lines.extend(
        f"#define {const_name('RETRO_IMAGE_', name):<30} {value}"
        for name, value in image
    )
    lines.append("")
    lines.extend(
        f"#define {const_name('RETRO_DICT_OFFSET_', name):<30} {value}"
        for name, value in dictionary
    )
    lines.extend(["", "#endif", ""])
    path.write_text("\n".join(lines), encoding="ascii")


def write_python(path, image, dictionary):
    lines = ["# Generated by tools/generate-layout.", "", "IMAGE = {"]
    lines.extend(f'    "{name}": {value},' for name, value in image)
    lines.extend(["}", "", "DICTIONARY = {"])
    lines.extend(f'    "{name}": {value},' for name, value in dictionary)
    lines.extend(["}", ""])
    path.write_text("\n".join(lines), encoding="ascii")


def write_js(path, image, dictionary):
    lines = ["/* Generated by tools/generate-layout. */", "", "var RETRO_IMAGE = Object.freeze({"]
    lines.extend(f"  {name}: {value}," for name, value in image)
    lines.extend(["});", "", "var RETRO_DICTIONARY = Object.freeze({"])
    lines.extend(f"  {name}: {value}," for name, value in dictionary)
    lines.extend(["});", ""])
    path.write_text("\n".join(lines), encoding="ascii")


def write_rust(path, image, dictionary):
    lines = ["// Generated by tools/generate-layout.", ""]
    lines.extend(
        f"pub const {const_name('IMAGE_', name)}: usize = {value};"
        for name, value in image
    )
    lines.append("")
    lines.extend(
        f"pub const {const_name('DICT_OFFSET_', name)}: usize = {value};"
        for name, value in dictionary
    )
    lines.append("")
    path.write_text("\n".join(lines), encoding="ascii")


def write_pascal(path, image, dictionary):
    lines = ["{ Generated by tools/generate-layout. }", "", "const"]
    lines.extend(
        f"  {const_name('RETRO_IMAGE_', name)} = {value};"
        for name, value in image
    )
    lines.append("")
    lines.extend(
        f"  {const_name('RETRO_DICT_OFFSET_', name)} = {value};"
        for name, value in dictionary
    )
    lines.append("")
    path.write_text("\n".join(lines), encoding="ascii")


def main():
    image = read_layout(LAYOUT / "image.tsv")
    dictionary = read_layout(LAYOUT / "dictionary.tsv")

    for directory in [
        ROOT / "tools" / "generated",
        ROOT / "vm" / "nga-c",
        ROOT / "vm" / "nga-python",
        ROOT / "vm" / "nga-js",
        ROOT / "vm" / "nga-rust",
        ROOT / "vm" / "nga-pascal",
    ]:
        directory.mkdir(parents=True, exist_ok=True)

    write_c_header(ROOT / "tools" / "generated" / "retro_layout.h", "RETRO_GENERATED_LAYOUT_H", image, dictionary)
    write_python(ROOT / "tools" / "generated" / "retro_layout.py", image, dictionary)
    write_c_header(ROOT / "vm" / "nga-c" / "layout.h", "RETRO_NGA_C_LAYOUT_H", image, dictionary)
    write_python(ROOT / "vm" / "nga-python" / "layout.py", image, dictionary)
    write_js(ROOT / "vm" / "nga-js" / "layout.js", image, dictionary)
    write_rust(ROOT / "vm" / "nga-rust" / "layout.rs", image, dictionary)
    write_pascal(ROOT / "vm" / "nga-pascal" / "layout.inc", image, dictionary)


if __name__ == "__main__":
    main()
