/* RETRO layout generator -------------------------------------
  Reads tools/layout/ *.tsv and emits small constants files for
  C, Python, JavaScript, Rust, and Pascal consumers.
  ---------------------------------------------------------- */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_ENTRIES 64
#define MAX_NAME    64
#define MAX_LINE   256

struct Entry {
  char name[MAX_NAME];
  int value;
};

struct Layout {
  struct Entry image[MAX_ENTRIES];
  int image_count;
  struct Entry dictionary[MAX_ENTRIES];
  int dictionary_count;
};

void fail(const char *message) {
  fprintf(stderr, "%s\n", message);
  exit(1);
}

void macro_name(const char *prefix, const char *name, char *out, size_t size) {
  size_t p = 0;
  size_t i;
  const char *s;

  for (s = prefix; *s && p + 1 < size; s++)
    out[p++] = *s;

  for (i = 0; name[i] && p + 1 < size; i++) {
    char c = name[i];
    if (c >= 'a' && c <= 'z')
      c = (char)(c - 'a' + 'A');
    else if (!((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')))
      c = '_';
    out[p++] = c;
  }
  out[p] = '\0';
}

void read_layout_file(const char *path, struct Entry *entries, int *count) {
  FILE *fp;
  char line[MAX_LINE];
  char name[MAX_NAME];
  int value;

  fp = fopen(path, "r");
  if (fp == NULL) {
    fprintf(stderr, "Unable to open %s\n", path);
    exit(1);
  }

  while (fgets(line, sizeof(line), fp) != NULL) {
    if (line[0] == '#' || line[0] == '\n' || line[0] == '\0')
      continue;

    if (sscanf(line, "%63s %d", name, &value) == 2) {
      if (*count >= MAX_ENTRIES)
        fail("Too many layout entries");
      strncpy(entries[*count].name, name, MAX_NAME - 1);
      entries[*count].name[MAX_NAME - 1] = '\0';
      entries[*count].value = value;
      *count += 1;
    }
  }

  fclose(fp);
}

void load_layout(struct Layout *layout) {
  layout->image_count = 0;
  layout->dictionary_count = 0;
  read_layout_file("tools/layout/image.tsv", layout->image, &layout->image_count);
  read_layout_file("tools/layout/dictionary.tsv", layout->dictionary, &layout->dictionary_count);
}

void write_c_header(const char *path, const char *guard, const struct Layout *layout) {
  FILE *fp;
  int i;
  char name[128];

  fp = fopen(path, "w");
  if (fp == NULL) {
    fprintf(stderr, "Unable to write %s\n", path);
    exit(1);
  }

  fprintf(fp, "#ifndef %s\n", guard);
  fprintf(fp, "#define %s\n\n", guard);
  fprintf(fp, "/* Generated by tools/generate-layout. */\n\n");

  for (i = 0; i < layout->image_count; i++) {
    macro_name("RETRO_IMAGE_", layout->image[i].name, name, sizeof(name));
    fprintf(fp, "#define %-30s %d\n", name, layout->image[i].value);
  }
  fprintf(fp, "\n");
  for (i = 0; i < layout->dictionary_count; i++) {
    macro_name("RETRO_DICT_OFFSET_", layout->dictionary[i].name, name, sizeof(name));
    fprintf(fp, "#define %-30s %d\n", name, layout->dictionary[i].value);
  }

  fprintf(fp, "\n#endif\n");
  fclose(fp);
}

void write_python(const char *path, const struct Layout *layout) {
  FILE *fp;
  int i;

  fp = fopen(path, "w");
  if (fp == NULL) {
    fprintf(stderr, "Unable to write %s\n", path);
    exit(1);
  }

  fprintf(fp, "# Generated by tools/generate-layout.\n\n");
  fprintf(fp, "IMAGE = {\n");
  for (i = 0; i < layout->image_count; i++)
    fprintf(fp, "    \"%s\": %d,\n", layout->image[i].name, layout->image[i].value);
  fprintf(fp, "}\n\n");
  fprintf(fp, "DICTIONARY = {\n");
  for (i = 0; i < layout->dictionary_count; i++)
    fprintf(fp, "    \"%s\": %d,\n", layout->dictionary[i].name, layout->dictionary[i].value);
  fprintf(fp, "}\n");
  fclose(fp);
}

void write_js(const char *path, const struct Layout *layout) {
  FILE *fp;
  int i;

  fp = fopen(path, "w");
  if (fp == NULL) {
    fprintf(stderr, "Unable to write %s\n", path);
    exit(1);
  }

  fprintf(fp, "/* Generated by tools/generate-layout. */\n\n");
  fprintf(fp, "var RETRO_IMAGE = Object.freeze({\n");
  for (i = 0; i < layout->image_count; i++)
    fprintf(fp, "  %s: %d,\n", layout->image[i].name, layout->image[i].value);
  fprintf(fp, "});\n\n");
  fprintf(fp, "var RETRO_DICTIONARY = Object.freeze({\n");
  for (i = 0; i < layout->dictionary_count; i++)
    fprintf(fp, "  %s: %d,\n", layout->dictionary[i].name, layout->dictionary[i].value);
  fprintf(fp, "});\n");
  fclose(fp);
}

void write_rust(const char *path, const struct Layout *layout) {
  FILE *fp;
  int i;
  char name[128];

  fp = fopen(path, "w");
  if (fp == NULL) {
    fprintf(stderr, "Unable to write %s\n", path);
    exit(1);
  }

  fprintf(fp, "// Generated by tools/generate-layout.\n\n");
  for (i = 0; i < layout->image_count; i++) {
    macro_name("IMAGE_", layout->image[i].name, name, sizeof(name));
    fprintf(fp, "pub const %s: usize = %d;\n", name, layout->image[i].value);
  }
  fprintf(fp, "\n");
  for (i = 0; i < layout->dictionary_count; i++) {
    macro_name("DICT_OFFSET_", layout->dictionary[i].name, name, sizeof(name));
    fprintf(fp, "pub const %s: usize = %d;\n", name, layout->dictionary[i].value);
  }
  fclose(fp);
}

void write_pascal(const char *path, const struct Layout *layout) {
  FILE *fp;
  int i;
  char name[128];

  fp = fopen(path, "w");
  if (fp == NULL) {
    fprintf(stderr, "Unable to write %s\n", path);
    exit(1);
  }

  fprintf(fp, "{ Generated by tools/generate-layout. }\n\n");
  fprintf(fp, "const\n");
  for (i = 0; i < layout->image_count; i++) {
    macro_name("RETRO_IMAGE_", layout->image[i].name, name, sizeof(name));
    fprintf(fp, "  %s = %d;\n", name, layout->image[i].value);
  }
  fprintf(fp, "\n");
  for (i = 0; i < layout->dictionary_count; i++) {
    macro_name("RETRO_DICT_OFFSET_", layout->dictionary[i].name, name, sizeof(name));
    fprintf(fp, "  %s = %d;\n", name, layout->dictionary[i].value);
  }
  fclose(fp);
}

int main(void) {
  struct Layout layout;

  load_layout(&layout);
  write_c_header("tools/generated/retro_layout.h", "RETRO_GENERATED_LAYOUT_H", &layout);
  write_python("tools/generated/retro_layout.py", &layout);
  write_c_header("vm/nga-c/layout.h", "RETRO_NGA_C_LAYOUT_H", &layout);
  write_python("vm/nga-python/layout.py", &layout);
  write_js("vm/nga-js/layout.js", &layout);
  write_rust("vm/nga-rust/layout.rs", &layout);
  write_pascal("vm/nga-pascal/layout.inc", &layout);

  return 0;
}
